services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance_tracker_backend_prod
    expose:
      - "8000"
    volumes:
      - ./data:/app/backend/data
      - backend_static:/app/backend/static
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,${DOMAIN:-localhost}
    networks:
      - finance_tracker_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance_tracker_frontend_prod
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://${DOMAIN:-localhost}/api
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - finance_tracker_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: finance_tracker_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - backend_static:/var/www/static
    depends_on:
      - backend
      - frontend
    networks:
      - finance_tracker_network
    restart: unless-stopped

volumes:
  backend_static:

networks:
  finance_tracker_network:
    driver: bridge
